### ISSUE TITLE
replace the execution of mk_SCRIPgridplio_enh.csh with the following code

### ISSUE THREAD

**Issue by ran-feng** [christophergeiger3/cesm-unifying-scripts#6]
Hi Chris,
In step1, let's replace the execution of mk_SCRIPgridplio_enh.csh with the following code to allow for flexibility. 

# add the following to step 1
cat >! input.scrip_grid << EOF
$nx $ny  # nx, ny are from config.h
${ocngridname}
${popgridfile}
${kmtgridfile}
${ocngridfile}
1
EOF
${scripdir}/grids/myconvertPOPT < input.scrip_grid

**Comment by christophergeiger3** [comment]
Hey @ran-feng ,

Sorry for the delay, I finally got a good opportunity to work on this today!

So, the good news is that this change was fairly easy to implement...
The bad news is that I found a fairly big (pre-existing) bug in my code that's causing some issues!

I think I'll merge the changes I made for #6 now, and open a new issue for the bug I mentioned.

**Comment by christophergeiger3** [comment]
Fixed in ea1585d5c3e784b98d884de0f4195fdecaefec38 , thank you! :+1:
