### ISSUE TITLE
Various steps are running multiple times, and not producing target files

### ISSUE THREAD

**Issue by christophergeiger3** [christophergeiger3/cesm-unifying-scripts#7]
I noticed when implementing #6 that various steps are not working as intended.

After running `make`, the command runs various steps more than once, as seen below:
![image](https://user-images.githubusercontent.com/20095580/79528152-393bd300-8037-11ea-9067-2f1d6061d4bc.png)

**Comment by christophergeiger3** [comment]
I believe this is what's happening:

- User runs `make`
- The rule for step one runs correctly, and generates the dependencies step two needs.
- The rule for step two runs, but fails at some step(s) to produce the required targets
- The rule for step three attempts to run, but is dependent on certain files that step two is supposed to generate.
- The rule for step three runs the rule for step two once for every dependency it has that is a target of step two's rule.

**Comment by christophergeiger3** [comment]
Actually, after taking a second look at this, it appears that step one might *also* be failing...
![image](https://user-images.githubusercontent.com/20095580/79533091-0c8eb800-8045-11ea-9f0b-b4c34c26cc84.png)
It appears that `myconvertPOPT` is throwing a file is not found error. I think what is happening is that the absolute path is too long of an input, so some of the input is being cut off. I'll try changing the input to use relative paths instead of absolute paths (which I normally try to avoid).

**Comment by christophergeiger3** [comment]
After some tribulations I discovered a way to calculate and store a relative path temporarily, but it's not pretty.... :fearful:
![image](https://user-images.githubusercontent.com/20095580/79535602-e9b3d200-804b-11ea-803f-d9ff1c324279.png)
584da240c2a3d8d54bfa15bd9beebd77bf4512b5
This might be an over-engineered solution, but it removes the file not found error, so I'll keep it (for now).

**Comment by christophergeiger3** [comment]
It looks like this fixed step one, but step two is still having issues. I believe the issue has something to do with this line in `config.sh` which I believe was different in previous versions:

```fatm=/glade/p/cesm/cseg/mapping/grids/${natm}_070727.nc```

**Comment by ran-feng** [comment]
This line calls an existing file in /glade/p/cesm/cseg/mapping/grids/. This file no longer exists. Change 070727 to 141008 should make this work.
